### PR TITLE
Optimisations for milestone 6

### PR DESCRIPTION
**Pull request by SamroodAli**
Create mutual friendships in table
A user accepting another user's request creates mutual friendships in friendships table
Also indexes and unique true for [user_id,friend_id] as well as [friend_id and user_id]
Please review my code. Thank you for your time and consideration.

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @SamroodAli  
Such a remarkable project you made :+1: ! Awesome README :100: !
Good job with the user model optimisation! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.

Users got links to this [artcile](https://explainextended.com/2009/03/07/selecting-friends/) and [stackoverflow](https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table) discussion as a hint.
- [ ] when friendship is confirmed, an additional row with reversed user-friend pair is created

```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
### User model
- [ ] In order to get all posts written by a user on their friends, students can use the simple method in the User model (in order to NOT do it with Enumerable)
```
# User model
def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
- [ ] PostsController#index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by SamroodAli** [comment]
Thank you for your time @umairarshadbutt. I have implemented all the requirements. Please review my code

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**This is a great project you have going on, well-done lad and thanks for implementing the changes requested earlier on**. 

### Well-done 💯 
    1. The app runs as expected. 👍🏽 

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [x] Currently, you have one test failing. Give this a quick fix and you should be good to go
Screenshot from 2021-05-25 14-14-50



#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Review by taiwo2 — APPROVED** [review]
# STATUS: APPROVED 🎉 
@SamroodAli Great job, All your tests Passed.
kindly prepare for your next Project

**Comment by SamroodAli** [comment]
Thank you @taiwo2 for reviewing my code, your time and consideration.

**Pull request merged**
